id = "kvs-cyberpunk-2077"
name = "KvS Cyberpunk 2077"
version = "1.0.2"
schema_version = 1
authors = ["notKvS"]
description = "Inspired by VS Code 2077 theme"
repository = "https://github.com/notKvS/2077-zed"